### ISSUE TITLE
Support Babel config settings in `i18nrc` 

### ISSUE THREAD

**Issue by TimKam** [signavio/i18n#12]
As our build is using Babel 5, we need to be able to overwrite/ignore `.babelrc` files when extracting messages. That's why we will introduce a change that allows adding Babel config settings to `.i18nrc` as follows:

```
{
    "fileName": "<PATH_TO_POT>",
    "babel": {
	    "babelrc": false,
	     ...<other babel settings>
	}
}
```

**Comment by jfschwarz** [comment]
released with v1.2.0
