### ISSUE TITLE
Extracted translator comments are wrongly written in generated POT file

### ISSUE THREAD

**Issue by Amorphis2** [signavio/i18n#32]
# General information and issue description
The Signavio i18n function provides an automatic extraction of all i18n calls into a POT (Portable Object Template) file according to the PO file Gettext standard, but comments provided by a developer in the code directed to the translators are currently extracted wrong.

When you have the following i18n call for example:
`// translators: Some helpful comment directed to the translator and provided by the developer` 
`i18n('Some message id to be translated')`

The corresponding POT entry will look as follows
`# Some helpful comment directed to the translator and provided by the developer`
`msgid "Some message id to be translated"`
`msgstr ""`

## Observed Behaviour
The extracted comment do not have the correct comment prefix. Currently its `#`

## Expected Behaviour
The extracted comment do have the correct comment prefix. It should be`#.` according to the Gettext standard you can find in the link below.

### For additional information to the Gettext syntax take a look here:
https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

### See how i18n calls result in the generated POT file here:
https://confluence.signavio.com/display/ENG/Signavio+Process+Manager+-+How+do+i18n+calls+result+in+the+generated+POT+file

**Comment by TimKam** [comment]
Can it be that you actually mean ``extracted comments`` and not ``translator comments``? :-)
Otherwise, this ticket doesn't make a lot of sense, because translator comments are specified as ``#`` by the gettext standard.

**Comment by Amorphis2** [comment]
Yes you are right. I mean exactly that, but my description is confusing in some points. I will adapt it accordingly. Thanks for your hint.
