### ISSUE TITLE
inline comments

### ISSUE THREAD

**Issue by daesungkim1** [signavio/i18n#35]
As per translator's requirement, I need to add some description for i18n string. currently the library only accepts special keyword( translators: ) in inline comment. it makes code ugly, especially in JSX.

ex1)
```
<span>
{// translators: 'button on manage data page'
i18n('Upload more data')}
</span>
```

ex2)
```
    result = `${days}${// translators: days
    i18n('d')}${hours > 0
        ? ` ${hours}${// translators: hours
          i18n('h')}`
        : ''}`
```

or sometimes I also need to add like this
```
    <SomeComponent
        label={// eslint-disable-next-line
        // translators: label of the select box in the process diagram widget
        i18n('Process diagram')}
/>
```

Can we also accepts the description as an argument?
```
<span>
{i18n('Upload more data', {translators: 'button on manage data page' })}
</span>
```

https://confluence.signavio.com/display/ENG/Signavio+Process+Manager+-+How+do+i18n+calls+result+in+the+generated+POT+file

**Comment by jfschwarz** [comment]
I would not like to support translator comments as an argument as it would mean that these comments cannot be code-minified away.

The second example you gave is a good use case for gettext context. I would write it as follows:

```
    result = [
      i18n('__days__d', { days, context: 'time unit days' })`,
      hours > 0 ? i18n(' __hours__h', { hours, context: 'time unit hours' })` : ''
   ].join('')
```

As you can see, using interpolations correctly here probably even makes setting the context obsolete.

**Comment by daesungkim1** [comment]
>  it would mean that these comments cannot be code-minified away. 

I missed the benefit of in-line comment line on the source code. 👍  That's correct. The description shouldn't be a part of source code and thank you for the way of improving code piece.
