### ISSUE TITLE
Support msgctxt

### ISSUE THREAD

**Issue by TimKam** [signavio/i18n#4]
We should support gettext's [msgctx](https://www.gnu.org/software/gettext/manual/html_node/Contexts.html).
The [gettext-parser](https://github.com/smhg/gettext-parser) library we use already supports this.

**Comment by jfschwarz** [comment]
There's already a rough implementation sketch for extracting message contexts in the extractor script: https://github.com/signavio/i18n/blob/master/src/scripts/babel-gettext-extractor/index.js#L143

**Comment by TimKam** [comment]
To me, it looks like the tests use a different .po file loader than the actual code and fixing the tests won't solve our problem, because the .po file loader that is used in the tests doesn't handle msgctxt elegantly. For example, the msgid `Export` with the msgctxt `button label` is available as: `button labelExport`, with `` being equal to `unescape('%04')`.
Do I understand this correctly?

**Comment by jfschwarz** [comment]
What do you mean by "actual code"? In Workflow we use the [po-loader](https://github.com/perchlayer/po-loader) just as the tests in this repo.

The po-loader uses [po2json](https://github.com/mikeedwards/po2json) under the hood, so you might check there for more details on handling of msgctxt.

**Comment by TimKam** [comment]
Thanks, now I understand.
